### ISSUE TITLE
Raspberry Pi Pico W

### ISSUE THREAD

**Issue by jorgechacblogspot** [OzmoOzmo/CastleHKCArduinoESP32#1]
https://github.com/earlephilhower/arduino-pico/issues/1433#issuecomment-1546783109%22)%60

"I hack/fixed the issue for myself by including these missing? files from Pico SDK 1.5 in my src folder... Im not sure if there is other code or libs missing - but this allows the above to compile and run and print to Terminal from the pico.

files: stdio_uart.h, stdio_usb.h, stdio.c, stdio_uart.c, stdio_usb.c, stdlib.c"

Hello OzmoOzmo, (sorry for asking here but there is no contact email in your github profile), to which specific paths should these files be copied?

**Comment by OzmoOzmo** [comment]
I put the c files (stdio.c, stdio_uart.c, stdio_usb.c, stdlib.c) into the lib folder for each project I was working on eg. 

\Blink\lib\uartcomms\src\

and the header files (stdio_uart.h, stdio_usb.h ) here: 
\Blink\lib\uartcomms\src\pico

Works well then - I can use the official Pico sdk - which was needed for my projects.

My Platformio looks like this:

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
board = pico
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
monitor_speed = 115200
build_flags = 
    -D PICO_STDIO_USB  ; not needed unless running without debugger
    -D PICO_STDIO_UART ; want real uart working as this is connected to picodebug
    ;-D DEBUG_RP2040_PORT=Serial

lib_deps = uartcomms ;*important* Ambroses library to fix print/uart issues
debug_speed = 5000


------sample c code:
#include <stdio.h>
#include "pico/stdlib.h"

#define LED_PIN 25
int main() {
    stdio_init_all();
    printf("Hello World...\n");
    gpio_init(LED_PIN);
    gpio_set_dir(LED_PIN, GPIO_OUT);
    while (true) {
         gpio_put(LED_PIN, 1);
         sleep_ms(25);
         gpio_put(LED_PIN, 0);
         sleep_ms(25);
    }
}

**Comment by jorgechacblogspot** [comment]
OK thank you for answering.
